library(mvtnorm)
set.seed(2000)
m_g = c(1,0)
m_r = c(0,1)
mu = rmvnorm(10,m_g,diag(2))
nu = rmvnorm(10,m_r,diag(2))
train_g = do.call(rbind,lapply(seq_len(100),function(i){rmvnorm(1,mu[sample(1:10,1),],diag(2)/5)}))
train_r = do.call(rbind,lapply(seq_len(100),function(i){rmvnorm(1,nu[sample(1:10,1),],diag(2)/5)}))
dtrain = cbind(rbind(train_g,train_r),rep(c(0,1),each=100))
colnames(dtrain) = c("x1","x2","y")
dtrain = as.data.frame(dtrain)
plot(dtrain$x1,dtrain$x2,xlab="x1",ylab="x2")
points(train_g,col="green")
points(train_r,col="red")

set.seed(2014)
test_g = do.call(rbind,lapply(seq_len(500),function(i){rmvnorm(1,mu[sample(1:10,1),],diag(2)/5)}))
test_r = do.call(rbind,lapply(seq_len(500),function(i){rmvnorm(1,nu[sample(1:10,1),],diag(2)/5)}))
dtest = cbind(rbind(test_g,test_r),rep(c(0,1),each=500))
colnames(dtest) = c("x1","x2","y")
dtest = as.data.frame(dtest)

wd = getwd()

save(dtrain,file=paste(wd,"/hw5_train.rda",sep=""))
save(dtest,file=paste(wd,"/hw5_test.rda",sep=""))
